---
section_name: 1면
page_heading_margin_in_lines: 
ad_type: 광고없음
is_front_page: 
profile: 6x15_광고없음_0
section_id: 1
page_columns: 6
grid_size:
- 171.49606299212348
- 
lines_per_grid: 
width: 
height: 
left_margin: 
top_margin: 
right_margin: 
bottom_margin: 
gutter: 
story_frames: []
article_line_thickness: 
draw_divider: 
