---
:width: 342.992125984246
:height: 1418.1327334083066
:pillar_frame:
- - 0
  - 0
  - 2
  - 3
  - '1'
- - 0
  - 3
  - 2
  - 3
  - '2'
- - 0
  - 6
  - 2
  - 3
  - '3'
- - 0
  - 9
  - 2
  - 3
  - '4'
- - 0
  - 12
  - 2
  - 3
  - '5'
